<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2020 Amasty (https://www.amasty.com)
 * @package Amasty_PromoBanners
 */
?>
<?php /* @var $block \Amasty\PromoBanners\Block\Banner */ ?>
<?php $banner = $block->getBanner() ?>

<div class="ampb-<?=$block->getBannerProductsLayout(); ?>-products-row <?= $block->getBannerCssClass(); ?>" data-banner-id="<?= $banner->getId(); ?>">
    <?= $block->getBannerText() ?>
    <?= $block->getChildHtml('product_listing') ?>
</div>
